# "docker compose up" or  "docker compose up -d" to run
# links  : rtsp://rtsp-server:8554/cam1
#          rtsp://rtsp-server:8554/cam2

services:
  rtsp-server:
    restart: unless-stopped
    ports:
      - "1935:1935"
      - "8554:8554"
      - "8888:8888"
    environment:
      - RTSP_PROTOCOLS=tcp
    image: bluenviron/mediamtx

  cam1:
    restart: unless-stopped
    image: linuxserver/ffmpeg:version-4.4-cli
    links:
      - "rtsp-server:rtsp-server"
    depends_on:
      - rtsp-server
    volumes:
      - ./video-samples/:/tmp/
    command: -re -stream_loop -1 -i /tmp/VIRAT_S_010115_03_000685_000793.mp4 -c copy -f rtsp rtsp://rtsp-server:8554/cam1


  cam2:
    restart: unless-stopped
    image: linuxserver/ffmpeg:version-4.4-cli
    links:
      - "rtsp-server:rtsp-server"
    depends_on:
      - rtsp-server
    volumes:
      - ./video-samples/:/tmp/
    command: -re -stream_loop -1 -i /tmp/VIRAT_S_010204_01_000072_000225.mp4 -c copy -f rtsp rtsp://rtsp-server:8554/cam2

  # cam3:
  #   restart: unless-stopped
  #   image: linuxserver/ffmpeg:version-4.4-cli
  #   links:
  #     - "rtsp-server:rtsp-server"
  #   depends_on:
  #     - rtsp-server
  #   volumes:
  #     - ./video-samples/:/tmp/
  #   command: -re -stream_loop -1 -i /tmp/VIRAT_S_050202_10_002159_002233.mp4 -c copy -f rtsp rtsp://rtsp-server:8554/cam3

  # cam4:
  #   restart: unless-stopped
  #   image: linuxserver/ffmpeg:version-4.4-cli
  #   links:
  #     - "rtsp-server:rtsp-server"
  #   depends_on:
  #     - rtsp-server
  #   volumes:
  #     - ./video-samples/:/tmp/
  #   command: -re -stream_loop -1 -i /tmp/VIRAT_S_050301_00_000000_000036.mp4 -c copy -f rtsp rtsp://rtsp-server:8554/cam4

  # cam5:
  #   restart: unless-stopped
  #   image: linuxserver/ffmpeg:version-4.4-cli
  #   links:
  #     - "rtsp-server:rtsp-server"
  #   depends_on:
  #     - rtsp-server
  #   volumes:
  #     - ./video-samples/:/tmp/
  #   command: -re -stream_loop -1 -i /tmp/VIRAT_S_050301_02_000544_000607.mp4 -c copy -f rtsp rtsp://rtsp-server:8554/cam5

  # webcam:
  #   restart: unless-stopped
  #   image: linuxserver/ffmpeg:version-4.4-cli
  #   devices:
  #     - /dev/video0:/dev/video0
  #   links:
  #     - "rtsp-server:rtsp-server"
  #   depends_on:
  #     - rtsp-server
  #   command: -f v4l2 -framerate 30 -video_size 1280x720 -i /dev/video0 -f rtsp rtsp://rtsp-server:8554/webcam

  # city-traffic:
  #   restart: unless-stopped
  #   image: linuxserver/ffmpeg:version-4.4-cli
  #   links:
  #     - "rtsp-server:rtsp-server"
  #   depends_on:
  #     - rtsp-server
  #   command: -re -stream_loop -1 -i https://eu-central-1.linodeobjects.com/savant-data/demo/Free_City_Street_Footage.mp4 -c copy -bsf:v h264_mp4toannexb -f rtsp rtsp://rtsp-server:8554/cam1
